// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoYROqIcWoNvNKS-F95f7x1O506G4r7nM',
    appId: '1:243891896311:web:2b98d6d05b4323d0ce78f2',
    messagingSenderId: '243891896311',
    projectId: 'flutteback',
    authDomain: 'flutteback.firebaseapp.com',
    storageBucket: 'flutteback.firebasestorage.app',
    measurementId: 'G-NWK45719TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKBYzb18a-axEmkv60wOfTj2SiUqcg6_s',
    appId: '1:243891896311:android:dc4144af9571eaf6ce78f2',
    messagingSenderId: '243891896311',
    projectId: 'flutteback',
    storageBucket: 'flutteback.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQjZ0jQUXlVtItPVIxKzFYd-DMij54MWs',
    appId: '1:243891896311:ios:22f06690e33877a5ce78f2',
    messagingSenderId: '243891896311',
    projectId: 'flutteback',
    storageBucket: 'flutteback.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQjZ0jQUXlVtItPVIxKzFYd-DMij54MWs',
    appId: '1:243891896311:ios:22f06690e33877a5ce78f2',
    messagingSenderId: '243891896311',
    projectId: 'flutteback',
    storageBucket: 'flutteback.firebasestorage.app',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoYROqIcWoNvNKS-F95f7x1O506G4r7nM',
    appId: '1:243891896311:web:931ff5cc6cf01592ce78f2',
    messagingSenderId: '243891896311',
    projectId: 'flutteback',
    authDomain: 'flutteback.firebaseapp.com',
    storageBucket: 'flutteback.firebasestorage.app',
    measurementId: 'G-2ECREGW5E7',
  );
}
