class ProductModel {
  final String id;
  final String name;
  final String price;
  final int priceValue;
  final bool isDark;
  final String? imageUrl;
  final String? imageAsset;
  final String category;
  final String shopId;

  const ProductModel({
    required this.id,
    required this.name,
    required this.price,
    required this.priceValue,
    this.isDark = false,
    this.imageUrl,
    this.imageAsset,
    required this.category,
    required this.shopId,
  });
}

const List<ProductModel> allProducts = [
  ProductModel(
    id: '1',
    name: 'Parfum Oud Rose',
    price: '1 200 MRU',
    priceValue: 1200,
    imageUrl: 'https://images.unsplash.com/photo-1541643600914-78b084683702?w=400&q=80',
    category: 'perfumes',
    shopId: 'shop_2',
  ),
  ProductModel(
    id: '2',
    name: 'Melhfa Élégante',
    price: '800 MRU',
    priceValue: 800,
    isDark: true,
    imageUrl: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=400&q=80',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: '3',
    name: 'Daraa Premium',
    price: '950 MRU',
    priceValue: 950,
    imageUrl: 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400&q=80',
    category: 'daraa',
    shopId: 'shop_homme',
  ),
  ProductModel(
    id: '4',
    name: 'Sac Cuir Artisanal',
    price: '2 500 MRU',
    priceValue: 2500,
    imageUrl: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=400&q=80',
    category: 'bags',
    shopId: 'shop_4',
  ),
  ProductModel(
    id: '5',
    name: 'Palette Maquillage',
    price: '650 MRU',
    priceValue: 650,
    imageUrl: 'https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400&q=80',
    category: 'makeup',
    shopId: 'shop_5',
  ),
  ProductModel(
    id: '6',
    name: 'Sérum Visage',
    price: '480 MRU',
    priceValue: 480,
    isDark: true,
    imageUrl: 'https://images.unsplash.com/photo-1556228720-da424861bd16?w=400&q=80',
    category: 'skincare',
    shopId: 'shop_5',
  ),
  ProductModel(
    id: '7',
    name: 'Sneakers Sport',
    price: '1 800 MRU',
    priceValue: 1800,
    imageUrl: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80',
    category: 'shoes',
    shopId: 'shop_4',
  ),
  ProductModel(
    id: '8',
    name: 'T-Shirt Premium',
    price: '350 MRU',
    priceValue: 350,
    imageUrl: 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=400&q=80',
    category: 'clothing',
    shopId: 'shop_4',
  ),
  ProductModel(
    id: '9',
    name: 'Jean Slim Fit',
    price: '750 MRU',
    priceValue: 750,
    isDark: true,
    imageUrl: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&q=80',
    category: 'clothing',
    shopId: 'shop_4',
  ),
  ProductModel(
    id: '10',
    name: 'Bracelet Or 18K',
    price: '5 000 MRU',
    priceValue: 5000,
    imageUrl: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80',
    category: 'jewelry',
    shopId: 'shop_3',
  ),
  ProductModel(
    id: '11',
    name: 'Montre Classique',
    price: '3 200 MRU',
    priceValue: 3200,
    isDark: true,
    imageUrl: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80',
    category: 'watches',
    shopId: 'shop_3',
  ),
  ProductModel(
    id: '12',
    name: 'iPhone Coque',
    price: '180 MRU',
    priceValue: 180,
    imageUrl: 'https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?w=400&q=80',
    category: 'phones',
    shopId: 'shop_6',
  ),
  ProductModel(
    id: '13',
    name: 'Coussin Déco',
    price: '290 MRU',
    priceValue: 290,
    imageUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80',
    category: 'home_decor',
    shopId: 'shop_6',
  ),
  ProductModel(
    id: '14',
    name: 'Balle de Football',
    price: '420 MRU',
    priceValue: 420,
    imageUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=400&q=80',
    category: 'sports',
    shopId: 'shop_6',
  ),
  ProductModel(
    id: '15',
    name: 'Rouge à Lèvres',
    price: '320 MRU',
    priceValue: 320,
    isDark: true,
    imageUrl: 'https://images.unsplash.com/photo-1586495777744-4e6232c8ec14?w=400&q=80',
    category: 'makeup',
    shopId: 'shop_5',
  ),
  ProductModel(
    id: '16',
    name: 'Crème Hydratante',
    price: '380 MRU',
    priceValue: 380,
    imageUrl: 'https://images.unsplash.com/photo-1608248543803-ba4f8c70ae0b?w=400&q=80',
    category: 'skincare',
    shopId: 'shop_5',
  ),

  // ── BELLAH DUBAI — 10 produits ──────────────────────────────────────────
  ProductModel(
    id: 'b1',
    name: 'Persi Japan',
    price: '12 000 MRU',
    priceValue: 12000,
    isDark: true,
    imageAsset: 'assets/persi_japan.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b2',
    name: 'Persi Japan Royale',
    price: '15 500 MRU',
    priceValue: 15500,
    isDark: false,
    imageAsset: 'assets/persi_japan.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b3',
    name: 'Persi Japan Prestige',
    price: '13 000 MRU',
    priceValue: 13000,
    isDark: true,
    imageAsset: 'assets/persi_japan.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b4',
    name: 'Persi Japan Premium',
    price: '17 000 MRU',
    priceValue: 17000,
    isDark: false,
    imageAsset: 'assets/persi_japan.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b5',
    name: 'Diana London',
    price: '25 000 MRU',
    priceValue: 25000,
    isDark: true,
    imageAsset: 'assets/diana_london.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b6',
    name: 'Diana London Collection',
    price: '19 500 MRU',
    priceValue: 19500,
    isDark: false,
    imageAsset: 'assets/diana_london.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b7',
    name: 'Melhfa Kati',
    price: '14 000 MRU',
    priceValue: 14000,
    isDark: true,
    imageAsset: 'assets/kati.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b8',
    name: 'Melhfa Kati Prestige',
    price: '18 000 MRU',
    priceValue: 18000,
    isDark: false,
    imageAsset: 'assets/kati.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b9',
    name: 'Melhfa Nessij',
    price: '16 500 MRU',
    priceValue: 16500,
    isDark: true,
    imageAsset: 'assets/nessij.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
  ProductModel(
    id: 'b10',
    name: 'Melhfa Nessij Premium',
    price: '20 000 MRU',
    priceValue: 20000,
    isDark: false,
    imageAsset: 'assets/nessij.jpg',
    category: 'melhfa',
    shopId: 'shop_bellah',
  ),
];
